### ISSUE TITLE
How does one access their project once configured? 

### ISSUE THREAD

**Issue by thinkstylestudio** [askaoru/LempFleet#1]
Hi, 

I'm giving LempFleet a go but I'm not 100% sure how to access `project1` or `project2` respectively (referencing your setup instructions).

For example if I have the `project1.test` set as the `server_name`. 

Should I not be able to simply add `project1.test` to my systems local `host` file and call it a day?

**Comment by rickjm540** [comment]
Similar problem - if I set up a project1.cnf with:
 server_name project1.test; # Change accordingly
and add that to my hosts file, I get:
curl: (52) Empty reply from server 

Any advice?

**Comment by DxCat** [comment]
Hello there, 
I'm sorry for the issues you are facing. Turns out I had a typo in the readme (it has been fixed),
the nginx config file should be a `.conf` file instead of `.cnf`

@rickjm540 do try to rename your `project1.cnf` into `project1.conf` and then run `docker-compose up -d` again.

@thinkstylestudio this should fix your issue as well, but do let me know if it still hasnt.

**Comment by rickjm540** [comment]
Gosh - I should have caught that - thanks for the quick reply - this is really a helpful project!

**Comment by rickjm540** [comment]
Hmmm - now I'm getting connection refused on the mysql instance, altho I can connect to it from the command line (outside of docker)...

**Comment by thinkstylestudio** [comment]
Whats's really weird is I'm getting the same issue I had as before. 

```
This page isn’t working
project1.test didn’t send any data.
ERR_EMPTY_RESPONSE
```

I have an empty `index.php` in `app/project1/` and `nginx/project1.conf` which contains the example you provided in the readme. I've added `127.0.0.1 project1.test` to `host` file. I'm on a mac.

**Comment by DxCat** [comment]
@thinkstylestudio I do not have a mac to test it, however can you try going into the webserver container, navigate to `/etc/nginx/conf.d` and check whether `project1.conf` file is there and that the root user in nginx container can access it properly? could be a permission issue.

@rickjm540 if you're still having issue with the mysql feel free to open a new issue for it

**Comment by thinkstylestudio** [comment]
Weird, I have a file named `project1.conf.cnf` I'm not sure how that stayed as such, but that is where the break is. I'm going to try and can all storage etc and rebuild it.

**Comment by rickjm540** [comment]
Got the mysql working - forgot that I had to use the container name instead of 127.0.0.1 for the db host. 
Thanks again!

**Comment by DxCat** [comment]
Hi @thinkstylestudio. Just following up. Do let me know if everything is working fine so I can close this ticket :)

**Comment by thinkstylestudio** [comment]
It works and ass seems good close away thanks!
